dist: trusty
language: python

# Existing Python versions
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip list & pip install -U setuptools && pip install -U tox-travis

script:
  - tox

after_success:
  - bash <(curl -s https://codecov.io/bash)
