# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"

env:
  - TOX_ENV=py37-django-20
  - TOX_ENV=py36-django-20
  - TOX_ENV=py35-django-20

matrix:
  fast_finish: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#   keep_history: true
#   on:
#     branch: master

# deploy:
#   provider: heroku
#   api_key: ...
#   app:
#     master: {{ cookiecutter.app_name }}-staging
#     development: {{ cookiecutter.app_name }}-development
#     production: {{ cookiecutter.app_name }}-production

# deploy:
    # provider: pypi
    # user: ...
    # password: ...
    # on:
      # tags: true
      # branch: master
    # skip_existing: true
    # distributions: "sdist bdist_wheel" # Your distributions here